[platformio]
src_dir = src

[env:audio_dock_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -I../shared
lib_extra_dirs =
  C:/Users/User/Documents/Arduino/libraries
lib_deps =
  ESP32-S3-Clap-Sensor_inferencing
  LiquidCrystal_I2C
  adafruit/Adafruit NeoPixel
