[platformio]
src_dir = src

[env:charging_dock_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3_tft
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -I../shared
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  adafruit/Adafruit INA219
  paulstoffregen/OneWire
  milesburton/DallasTemperature
